######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 22 11:15:37 2017
######################################################################

TEMPLATE = app
TARGET = picsmagick
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += canvas.h main.h exif.h tools.h
FORMS += mainwindow.ui
SOURCES += canvas.cpp main.cpp exif.cpp tools.cpp
RESOURCES += resources.qrc